# Generated by Django 5.0.1 on 2024-01-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0002_alter_seed_obtaintime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='plantImg',
            field=models.ImageField(default='default.jpg', upload_to='plant_pics'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='seedImg',
            field=models.ImageField(upload_to='seed_pics'),
        ),
    ]
