# Generated by Django 5.0.1 on 2024-01-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_alter_step_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
