# Generated by Django 5.0.1 on 2024-02-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_alter_seed_plantimg_alter_seed_seedimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='seedName',
            field=models.CharField(max_length=50),
        ),
    ]
