# Generated by Django 5.0.1 on 2024-02-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0009_alter_seed_seedname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='obtainTime',
            field=models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall'), ('winter', 'winter'), ('any season', 'any season')], default='any season', max_length=20),
        ),
    ]
