# Generated by Django 5.0.1 on 2024-01-25 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_step_post_year_seed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='seed',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='seed',
            name='edibleFruit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seed',
            name='growthRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seed',
            name='obtainTime',
            field=models.CharField(choices=[('Jan', 'January'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='Jan', max_length=3),
        ),
        migrations.AddField(
            model_name='seed',
            name='plantImg',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('Jan', 'January'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=3),
        ),
    ]
