# Generated by Django 5.0.1 on 2024-01-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_delete_step_seed_date_posted_seed_ediblefruit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to=None)),
                ('content', models.TextField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.seed')),
            ],
        ),
    ]
