# Generated by Django 5.0.1 on 2024-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='content',
            field=models.TextField(default='Content for this seed'),
            preserve_default=False,
        ),
    ]
