# Generated by Django 5.0.1 on 2024-01-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_seed_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
        migrations.DeleteModel(
            name='Seed',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
