# Generated by Django 5.0.1 on 2024-02-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_step_seed_remove_post_year_delete_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default_seed_pic.PNG', upload_to='seed_pics'),
        ),
    ]
