# Generated by Django 5.0.1 on 2024-08-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
