# Generated by Django 5.0.1 on 2024-11-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_remove_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
