# Generated by Django 5.0.1 on 2024-01-27 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed', '0006_delete_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default_seed_pic.PNG', upload_to='step_pics')),
                ('content', models.TextField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.seed')),
            ],
        ),
    ]
